name: ci

on:
    push:
        branches:
            - master

jobs:
    tests_e2e:
        name: Run e2e tests
        runs-on: ubuntu-latest
        env:
            CI: true
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Lint
              run: npm run lint
            - name: Install playwright browsers
              run: npx playwright install --with-deps
            - name: Run tests
              run: npx run test
