name: deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            deployments: write
        env:
            CI: true
        steps:
            - uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Lint
              run: npm run lint

            - name: Deploy app build to S3 bucket
              run: aws s3 sync dist/ s3://prod-site-andretorgal-com --acl public-read

            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
                  PATHS: '/*'
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
